### ISSUE TITLE
Hang due to WebSocket closing due to buffer overflow

### ISSUE THREAD

**Issue by karlvr** [kklisura/chrome-devtools-java-client#25]
If the WebSocket closes, `chrome-devtools-java-client` just hangs as it does not listen to or respond to the socket close event.

This causes an issue when printing large PDFs and requesting the result back as base64, as the WebSocket implementation has a maximum message size of 4MB. I have written this up https://superuser.com/questions/1472051/headless-chrome-hangs-when-trying-to-print-page-as-pdf/1483423#1483423

I note there is a [TODO in place of the `onClose` implementation](https://github.com/kklisura/chrome-devtools-java-client/blob/196992f40d1e26f0a31cf0fe7b99ba607297d0e0/cdt-java-client/src/main/java/com/github/kklisura/cdt/services/impl/WebSocketServiceImpl.java#L101) but I'm not sure how to implement it so that we can bubble the error back up, or where it should bubble back up to! I'd be happy to contribute a patch with a little guidance, or patiently await a patch if it's out of my league.

**Comment by kklisura** [comment]
Hi, thanks for using the library and thanks for debugging this issue. I really appreciate it! 🎊 

I've just release snapshot version `2.1.0-SNAPSHOT` that fixes this. I've:
  - Increased the default tyrus buffer size to 8MB instead of 4 [DefaultWebSocketContainerFactory.java](https://github.com/kklisura/chrome-devtools-java-client/blob/master/cdt-java-client/src/main/java/com/github/kklisura/cdt/services/factory/impl/DefaultWebSocketContainerFactory.java)
  - Provided an info message when buffer overflow raises again even with new buffer size
  - Provided a means to increase buffer size even more; Added example on how to do this ([ConfigurableTyrusClientFactory.java](https://github.com/kklisura/chrome-devtools-java-client/blob/master/cdt-java-client/src/main/java/com/github/kklisura/cdt/services/factory/impl/ConfigurableTyrusClientFactory.java), [IncreasedIncomingBufferInTyrusExample.java](https://github.com/kklisura/chrome-devtools-java-client/blob/master/cdt-examples/src/main/java/com/github/kklisura/cdt/examples/IncreasedIncomingBufferInTyrusExample.java))
  - Provided more visibility by logging connection states

If everything is ok, I'll be releasing it in soon.

**Comment by karlvr** [comment]
Thank you! I've checked out the changes in eae2ec6750dd11b89439d7e8c0ff31bf705b35dd.

Am I correct in thinking that the closing of the websocket won't trigger an exception in the client code? Ideally it should, otherwise the client code will still hang? Apologies if I've misunderstood it.

Also perhaps the buffer overflow note should be at WARN level? It does seem to indicate a problem!

Thank you for this package. It's very useful.

**Comment by kklisura** [comment]
I've released this as `2.1.0` with increased buffer size to 8 MB and means to change it if needed. 

As for the raising exceptions this isn't possible at the moment without rewriting or changing underlying web socket client. Read timeout can be set via [ChromeDevToolsServiceConfiguration](https://github.com/kklisura/chrome-devtools-java-client/blob/master/cdt-java-client/src/main/java/com/github/kklisura/cdt/services/config/ChromeDevToolsServiceConfiguration.java#L40) so at least timeout exception can occur.
